### ISSUE TITLE
GitHub login errors

### ISSUE THREAD

**Issue by b2times4** [vgrafe/nextjs-auth0#1]
- deployed to Now (also tried on localhost)
- created social connection with github on Auth0
- entered vars in .env file in root of project

- went to login screen and entered my github credentials:
The http://localhost:3000/callback page (and the one on Now) spits out this error (keep in mind I m not on https)

**Unhandled Rejection (InvalidTokenError): Invalid token specified**

./node_modules/jwt-decode/lib/index.js
./node_modules/jwt-decode/lib/index.js:9
__webpack_require__
./webpack/bootstrap:792
  789 | // Execute the module function
  790 | var threw = true;
  791 | try {
> 792 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  793 | 	threw = false;
  794 | } finally {
  795 | 	if(threw) delete installedModules[moduleId];
View compiled
fn
./webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {

**Comment by vgrafe** [comment]
Thanks for filing the issue! I completely forgot to add in the readme that I did only test for email/password auth. I'll have a look at social login after work.

**Comment by b2times4** [comment]
no worries - just very happy with this repo. Hope you can find the time to make this into a powerful solution for people that are looking for a auth0 + next combo

**Comment by vgrafe** [comment]
Tried on my end with success - just follow [the instructions here](https://auth0.com/docs/connections/social/github) and github will work out of the box.
